# Generated by Django 6.0.6 on 2026-08-04 04:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sosalert_activitylog_familyinvitation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_permission', models.CharField(choices=[('always', 'Always Share'), ('school_hours', 'School Hours Only'), ('safe_places', 'Safe Places Only'), ('emergencies_only', 'Emergencies Only'), ('paused', 'Paused'), ('approximate', 'Approximate Location')], max_length=20)),
                ('requested_permission', models.CharField(choices=[('always', 'Always Share'), ('school_hours', 'School Hours Only'), ('safe_places', 'Safe Places Only'), ('emergencies_only', 'Emergencies Only'), ('paused', 'Paused'), ('approximate', 'Approximate Location')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_permission_requests', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_permission_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
