# Generated by Django 6.0.6 on 2026-08-05 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_rename_notificatio_recipie_123456_idx_notificatio_recipie_a972ce_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_online', 'Friend Online'), ('friend_request', 'Friend Request'), ('friend_request_accepted', 'Friend Request Accepted'), ('friend_request_rejected', 'Friend Request Rejected'), ('location_request', 'Location Request'), ('location_accepted', 'Location Accepted'), ('location_rejected', 'Location Rejected'), ('family_invitation', 'Family Invitation'), ('family_request_accepted', 'Family Request Accepted'), ('sos_alert', 'SOS Alert')], max_length=30),
        ),
    ]
