from django.urls import path
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from .views import (
    FriendsListView,
    RegisterView,
    LoginView,
    ProfileView,
    ChangePasswordView,
    ForgotPasswordView,
    ResetPasswordView,
    UserSearchView,
    SendFriendRequestView,
    AcceptFriendRequestView,
    RejectFriendRequestView,
    UpdateIPAddressView,
    UpdateLocationView,
    OnlineStatusView,
    PendingLocationRequestsView,
    GuardianDashboardView,
    GuardianProfileView,
    FamilyMemberListCreateView,
    SafePlaceListCreateView,
    EmergencyContactListCreateView,
    FamilyInvitationView,
    RespondFamilyInvitationView,
    FamilyMembersView,
    RemoveFamilyMemberView,
    LocationPermissionView,
    SOSAlertListCreateView,
    ResolveSOSAlertView,
    RouteHistoryView,
    ActivityLogView,
    FamilyMapDataView,
    PermissionRequestView,
)
from notifications.views import RequestLocationView, RespondLocationRequestView

urlpatterns = [
    path("register/", RegisterView.as_view(), name="register"),
    path("login/", LoginView.as_view(), name="login"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("change-password/", ChangePasswordView.as_view(), name="change_password"),
    path("forgot-password/", ForgotPasswordView.as_view(), name="forgot_password"),
    path("reset-password/<uidb64>/<token>/", ResetPasswordView.as_view(), name="reset_password"),
    path( "users/search/", UserSearchView.as_view(), name="user_search"),
    path("friend-requests/", SendFriendRequestView.as_view(), name="friend_requests",),
    path("friend-requests/<int:pk>/accept/", AcceptFriendRequestView.as_view(), name="accept_friend_request",),
    path("friend-requests/<int:pk>/reject/", RejectFriendRequestView.as_view(), name="reject_friend_request",),
    path(
    "friends/",
    FriendsListView.as_view(),
    name="friends_list",
    ),
    path(
    "update-ip/",
    UpdateIPAddressView.as_view(),
    name="update_ip",
    ),
    path(
    "update-location/",
    UpdateLocationView.as_view(),
    name="update_location",
    ),
    path(
    "request-location/",
    RequestLocationView.as_view(),
    name="request_location",
    ),
    path(
    "location-requests/<int:pk>/respond/",
    RespondLocationRequestView.as_view(),
    name="respond_location_request",
    ),
    path(
    "online-status/",
    OnlineStatusView.as_view(),
    name="online_status",
    ),
    path(
        "location-requests/pending/",
        PendingLocationRequestsView.as_view(),
        name="pending_location_requests",
    ),
    path(
        "guardian/dashboard/",
        GuardianDashboardView.as_view(),
        name="guardian_dashboard",
    ),
    path(
        "guardian/profile/",
        GuardianProfileView.as_view(),
        name="guardian_profile",
    ),
    path(
        "guardian/family-members/",
        FamilyMemberListCreateView.as_view(),
        name="guardian_family_members",
    ),
    path(
        "guardian/safe-places/",
        SafePlaceListCreateView.as_view(),
        name="guardian_safe_places",
    ),
    path(
        "guardian/emergency-contacts/",
        EmergencyContactListCreateView.as_view(),
        name="guardian_emergency_contacts",
    ),
    path(
        "guardian/invitations/",
        FamilyInvitationView.as_view(),
        name="guardian_invitations",
    ),
    path(
        "guardian/invitations/<int:pk>/respond/",
        RespondFamilyInvitationView.as_view(),
        name="guardian_invitation_respond",
    ),
    path(
        "guardian/family/",
        FamilyMembersView.as_view(),
        name="guardian_family",
    ),
    path(
        "guardian/family/<int:user_id>/remove/",
        RemoveFamilyMemberView.as_view(),
        name="guardian_family_remove",
    ),
    path(
        "guardian/permissions/",
        LocationPermissionView.as_view(),
        name="guardian_permissions",
    ),
    path(
        "guardian/sos/",
        SOSAlertListCreateView.as_view(),
        name="guardian_sos",
    ),
    path(
        "guardian/sos/<int:pk>/resolve/",
        ResolveSOSAlertView.as_view(),
        name="guardian_sos_resolve",
    ),
    path(
        "guardian/route/",
        RouteHistoryView.as_view(),
        name="guardian_route",
    ),
    path(
        "guardian/activity/",
        ActivityLogView.as_view(),
        name="guardian_activity",
    ),
    path(
        "guardian/map-data/",
        FamilyMapDataView.as_view(),
        name="guardian_map_data",
    ),
    path(
        "guardian/permission-requests/",
        PermissionRequestView.as_view(),
        name="guardian_permission_requests",
    ),
]